[package]
name = "nutrient_calculator"
version = "1.2.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.20.0", features = ["extension-module"] }

[lib]
name = "nutrient_calculator"
crate-type = ["cdylib"]


[profile.release]
opt-level = "z"
lto = true
codegen-units = 1