[build-system]
requires = ["maturin>=1.5.1"]
build-backend = "maturin"

[tool.maturin]
name = "nutrient_calculator"
version = "1.1.0"
authors = ["Volodymyr Lekhman <volodya.l@yahoo.com>"]
description = "My Rust library for Python"